### PR TITLE
[IT-1234] Allow VPN access

### PR DESCRIPTION
**Pull request by zaro0508**
* Use update EC2 template which includes SG ingress to allow
AWS VPN access to instance.
* Update parameters to match new template

depends on https://github.com/Sage-Bionetworks/aws-infra/pull/338

### CODE REVIEW

**Review by ahayden — APPROVED** [review]
I expect the dgutman and xdoan instances are no longer needed.

**Comment by zaro0508** [comment]
> I expect the dgutman and xdoan instances are no longer needed.

last i checked @BrunoGrandePhD says we should keep them.

**Comment by BrunoGrandePhD** [comment]
@zaro0508: Not sure if/when you asked me about these two instances. I don't have context since they were created in May 2020 (I joined Sage in August 2020). 

We will likely be able to delete the two stacks, but I've asked others just in case. Stay tuned.

**Comment by BrunoGrandePhD** [comment]
@zaro0508: You can delete `dgutman-htan-new2-ec2` and `xdoan-htan-ec2` stacks.

**Comment by BrunoGrandePhD** [comment]
@zaro0508: You can delete `dgutman-htan-new2-ec2` and `xdoan-htan-ec2` stacks.

**Pull request merged**
