### PR TITLE
remove Xa's EC2 instances

### PR DESCRIPTION
**Pull request by zaro0508**
we are deprecating the PR provisioner.

### CODE REVIEW

**Review by xschildw — COMMENTED** [review]
Please hold, I'll have a look this week-end.

**Comment by zaro0508** [comment]
you still need these instances @xschildw ?

**Comment by zaro0508** [comment]
have you taken a look at your instances @xschildw ?

**Comment by xschildw** [comment]
@zaro0508 , yes these instances are stopped. Go ahead. Thx!

**Pull request merged**
