### PR TITLE
remove file to terminate instance

### PR DESCRIPTION
**Pull request by kdaily**

### CODE REVIEW

**Comment by thomasyu888** [comment]
@kdaily I dont have write access, but I removed the stack and approved

**Comment by kdaily** [comment]
Argh. Found an error in what I generated. I need this up again.

**Comment by kdaily** [comment]
Wait, did it stop before the PR was merged??!?!

**Comment by thomasyu888** [comment]
So the removal is not automated.

**Comment by zaro0508** [comment]
the instance was terminated (not sure why or by who) I reran the build which re-created the instance.

**Pull request closed without merging**
